name: 🐞 Bug Report
description: Create a report to help us improve
labels: [bug]
assignees: []
body:
  - type: dropdown
    id: os
    attributes:
      label: What system are you running duckdb.yazi on?
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: input
    id: terminal
    attributes:
      label: What terminal are you running Yazi in?
      placeholder: "ex: kitty v0.32.2"
    validations:
      required: true
  - type: input
    id: yazi_version
    attributes:
      label: What version of yazi are you using?
      placeholder: "ex: 25.4.8"
    validations:
      required: true
  - type: input
    id: duckdb_version
    attributes:
      label: What version of duckdb are you using?
      placeholder: "ex: 1.2.2"
    validations:
      required: true
  - type: dropdown
    id: latest_version_of_duckdb_yazi
    attributes:
      label: Have you upgraded to the latest version of duckdb.yazi?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label: Minimal reproducer
      description: A [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example) is required, otherwise the issue might be closed without further notice.
      placeholder: |
        Please include as much information as possible that can help to reproduce and understand the issue.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: |
        Add any other context about the problem here.  You can attach screenshots by clicking
        this area to highlight it and then drag the files in.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting the issue, please make sure you have completed the following
      options:
        - label: I upgraded to the latest versions of yazi, duckdb, and yazi.duckdb and the issue is still reproducible
          required: true
